### ISSUE TITLE
Not able to Install great_expectations

### ISSUE THREAD

**Issue by rishabhgupta28** [great-expectations/great_expectations#10351]
Getting below error while sending setting up great_expectations.
`(new_venv) (base) Rishabh_Gupta@M-C02FG03EMD6V ~ % great_expectations --version

Traceback (most recent call last):
  File "/Users/Rishabh_Gupta/new_venv/bin/great_expectations", line 5, in <module>
    from great_expectations.cli import main
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/great_expectations/__init__.py", line 6, in <module>
    from great_expectations.data_context.migrator.cloud_migrator import CloudMigrator
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/great_expectations/data_context/__init__.py", line 1, in <module>
    from great_expectations.data_context.data_context import (
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/great_expectations/data_context/data_context/__init__.py", line 1, in <module>
    from great_expectations.data_context.data_context.abstract_data_context import (
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 61, in <module>
    from great_expectations.core.datasource_dict import CacheableDatasourceDict
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/great_expectations/core/datasource_dict.py", line 13, in <module>
    from great_expectations.datasource.fluent import Datasource as FluentDatasource
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/great_expectations/datasource/fluent/__init__.py", line 5, in <module>
    from great_expectations.datasource.fluent.interfaces import (
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/great_expectations/datasource/fluent/interfaces.py", line 739, in <module>
    class Batch(FluentBaseModel):
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/pydantic/main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/pydantic/main.py", line 808, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/pydantic/typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/pydantic/typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Rishabh_Gupta/new_venv/lib/python3.12/site-packages/pydantic/typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
(new_venv) (base) Rishabh_Gupta@M-C02FG03EMD6V ~ % 
`

Also tried below steps to overcome with the error but no luck.
rm -rf <path_to_new_venv>
python3 -m venv <path_to_new_venv>
source <path_to_new_venv>/bin/activate

pip install pydantic==1.10.12 great_expectations

**Comment by adeola-ak** [comment]
did this error come as a result of you trying to check the version or running the install script? can you try checking the version with this instead:

```
import great_expectations as gx

print(gx.__version__)
```

**Comment by adeola-ak** [comment]
closing this issue as I believe the error stems from using a CLI command that is deprecated. to confirm your GX version, please use 

```
import great_expectations as gx

print(gx.__version__)
```
