### ISSUE TITLE
RuntimeBatchRequest object has no attribute 'options'

### ISSUE THREAD

**Issue by Bidek56** [great-expectations/great_expectations#10712]
Using the following code:

```
import os
os.environ["GX_ANALYTICS_ENABLED"] = "false"

import great_expectations as gx
import pandas as pd
from great_expectations.core.batch import RuntimeBatchRequest

context = gx.get_context()

data_source = context.data_sources.add_pandas("data_source")
data_asset = data_source.add_dataframe_asset("data_asset")
batch_definition = data_asset.add_batch_definition_whole_dataframe( "data_batch")

suite = context.suites.add(gx.ExpectationSuite("suite",
        expectations=[ gx.expectations.ExpectColumnValueLengthsToBeBetween(column="Track", min_value=1, max_value=4),],
    ))

dataframe = pd.DataFrame({'value': [0.10, 0.01]})

runtime_batch_request = RuntimeBatchRequest(
    datasource_name="data_source",
    data_connector_name="runtime_data_connector_name",
    data_asset_name="data_asset",
    runtime_parameters={"batch_data": dataframe},
    batch_identifiers={ "default_identifier_name": "run_id", },
)
batch = context.get_validator(
    batch_request=runtime_batch_request,
    expectation_suite_name="suite",
)
```
I get the following error:
```
Traceback (most recent call last):
  File "pvalidate2.py", line 41, in <module>
    batch = context.get_validator(
            ^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 1114, in get_validator
    batch_list = self._get_batch_list_from_inputs(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 1199, in _get_batch_list_from_inputs
    self.get_last_batch(
  File ".venv/lib/python3.12/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 1392, in get_last_batch
    return self._get_last_batch(
           ^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 1473, in _get_last_batch
    return datasource.get_batch(batch_request=result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/great_expectations/datasource/fluent/interfaces.py", line 775, in get_batch
    return data_asset.get_batch(batch_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/great_expectations/datasource/fluent/pandas_datasource.py", line 453, in get_batch
    self._validate_batch_request(batch_request)
  File ".venv/lib/python3.12/site-packages/great_expectations/datasource/fluent/pandas_datasource.py", line 430, in _validate_batch_request
    and batch_request.options
        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RuntimeBatchRequest' object has no attribute 'options'
```

**Environment:**
 - Operating System: MacOS  Darwin Kernel Version 23.6.0
 - Great Expectations Version: 1.2.4
 - Data Source: Pandas

**Comment by Bidek56** [comment]
Replacing `RuntimeBatchRequest` with `FluentBatchRequest` seems to solve the problem, but it would be nice for the docs to mention something. 
```
runtime_batch_request = FluentBatchRequest(
    datasource_name="data_source",
    data_asset_name="data_asset",
    options={ 'dataframe': dataframe }
)
```

**Comment by adeola-ak** [comment]
You don't need to use RuntimeBatchRequest or FluentBatchRequest in version 1.2.4. Additionally, get_validator is deprecated. I recommend reviewing our updated documentation, as version 1 introduced significant breaking changes aimed at simplifying workflows. You can find guidance on correctly validating a Pandas DataFrame in our documentation [here](https://docs.greatexpectations.io/docs/core/connect_to_data/dataframes/).

Heres a quick working example:
```
import great_expectations as gx
import pandas as pd

context = gx.get_context(mode="ephemeral")

name = "main"
bd = (
    context.data_sources.add_pandas(name)
    .add_dataframe_asset(name)
    .add_batch_definition_whole_dataframe(name)
)

suite = context.suites.add(
    gx.ExpectationSuite(
        name,
        expectations=[
            gx.expectations.ExpectColumnDistinctValuesToBeInSet(column="a", value_set=[1, 2, 3]),
            gx.expectations.ExpectColumnMaxToBeBetween(column="a", min_value=1, max_value=2),
        ],
    )
)

vd = context.validation_definitions.add(gx.ValidationDefinition(name=name, data=bd, suite=suite))
cp = context.checkpoints.add(
    gx.Checkpoint(
        name=name,
        validation_definitions=[vd],
        actions=[gx.checkpoint.actions.UpdateDataDocsAction(name=name)],
    )
)

cp.run(batch_parameters={"dataframe": pd.DataFrame({"a": [1, 2, 3]})})

context.open_data_docs()
```

As it appears everything is working as expected for V1, I'll be closing this issue but feel free to comment if you still need help.
