### ISSUE TITLE
[BUG] Sqlalchemy issue when upgrading GX

### ISSUE THREAD

**Issue by itaise** [great-expectations/great_expectations#7662]
Hi, 
We are using GX in Airflow, and trying to upgrade from GX 0.15.44 to version 0.16.7. 
When running our sanity tests, we started to get an error which Im not sure what cause it: 

```
[2023-04-20, 11:13:48 UTC] {warnings.py:110} WARNING - /root/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py:2731: DeprecationWarning: create_expectation_suite is deprecated as of v0.15.48 and will be removed in v0.18. Please use add_expectation_suite or add_or_update_expectation_suite instead.
  DeprecationWarning,

[2023-04-20, 11:13:48 UTC] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 3105, in __init__
    cols_present = bool(columns)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 535, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/root/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/root/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/root/.local/lib/python3.7/site-packages/wixflow/operators/ge_wix_operator.py", line 76, in execute
    self.prepare_data_context(context)
  File "/root/.local/lib/python3.7/site-packages/wixflow/operators/ge_wix_operator.py", line 93, in prepare_data_context
    env=self.get_env_from_trino_source(self.trino_source))
  File "/root/.local/lib/python3.7/site-packages/wixflow/operators/ge_wix_operator.py", line 187, in add_user_expectations
    suite: ExpectationSuite = self.create_suite(data_context, expectation_suite_name)
  File "/root/.local/lib/python3.7/site-packages/wixflow/operators/ge_wix_operator.py", line 193, in create_suite
    return data_context.create_expectation_suite(expectation_suite_name=suite_name, overwrite_existing=True)
  File "/root/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2735, in create_expectation_suite
    overwrite_existing=overwrite_existing,
  File "/root/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2876, in _add_expectation_suite
    **kwargs,
  File "/root/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2895, in _persist_suite_with_store
    persistence_fn(key=key, value=expectation_suite, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 226, in add_or_update
    self.key_to_tuple(key), self.serialize(value), **kwargs
  File "/root/.local/lib/python3.7/site-packages/great_expectations/data_context/store/_store_backend.py", line 156, in add_or_update
    if self.has_key(key):
  File "/root/.local/lib/python3.7/site-packages/great_expectations/data_context/store/_store_backend.py", line 167, in has_key
    return self._has_key(key)
  File "/root/.local/lib/python3.7/site-packages/great_expectations/data_context/store/database_store_backend.py", line 325, in _has_key
    sa.select(sa.func.count(column("value")))
  File "<string>", line 2, in select
  File "<string>", line 2, in __init__
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 3112, in __init__
    replace_context=err,
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: columns argument to select() must be a Python list or other iterable
[2023-04-20, 11:13:48 UTC] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ge_sanity, task_id=run_titanic_table_tests, execution_date=20230416T083349, start_date=20230420T111331, end_date=20230420T111348
[2023-04-20, 11:13:48 UTC] {standard_task_runner.py:92} ERROR - Failed to execute job 24 for task run_titanic_table_tests
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 3105, in __init__
    cols_present = bool(columns)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 535, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined

```

Did anything change that might cause this error? Im finding it difficult to understand the cause of it. 

Thanks a lot!

**Environment:** 
 - Great Expectations Version: 0.16.7
- sqlalchemy  1.3.24
- pydantic 1.9.2
- airflow - 2.2.3
- airflow-provider-great-expectations==0.1.4

**Comment by 1i1it** [comment]
Hey @itaise! Thanks for raising this.
Unfortunately we don't support sqlalchemy 1.3.24. You would need sqlalchemy ^1.4.
Would you mind upgrading sqlalchemy and checking if the issue still occurs?
Thanks!

**Comment by 1i1it** [comment]
closing this, feel free to reopen if there's any additional context!
