### ISSUE TITLE
Using snowflake as a Metrics store fails due to wrong primary_keys sqlalchemy query

### ISSUE THREAD

**Issue by manugarri** [great-expectations/great_expectations#7704]
**Describe the bug**
At my company we use Snowflake as our data warehouse, and we are starting to use GX for dataqa. Because we want to have historical tracking of which checks fail more frequently, im exploring implementing a metricsStore.

Im following the tutorial [here](https://docs.greatexpectations.io/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_metricsstore/) . 
Based on both the document, as well as some information from a GX member on the official slack channel, I believe the implementation should work.

![image](https://user-images.githubusercontent.com/3670355/233944606-54484a0e-72d5-4c5a-aa23-32ea1732f003.png)

However, running a metric store with a snowflake connection string fails with the following error:
```
Traceback (most recent call last):
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/cli/cli.py", line 202, in main
    cli()
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/cli/checkpoint.py", line 71, in checkpoint
    ctx.obj.data_context = ctx.obj.get_data_context_from_config_file()
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/cli/cli.py", line 48, in get_data_context_from_config_file
    context: FileDataContext = toolkit.load_data_context_with_error_handling(  # type: ignore[assignment] # will exit if error
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/cli/toolkit.py", line 412, in load_data_context_with_error_handling
    context = get_context(context_root_dir=directory)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/util.py", line 1941, in get_context
    return FileDataContext(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/data_context/file_data_context.py", line 60, in __init__
    super().__init__(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/data_context/serializable_data_context.py", line 67, in __init__
    super().__init__(runtime_environment=runtime_environment)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 318, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 280, in __init__
    self._init_stores(self.project_config_with_variables_substituted.stores)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 4449, in _init_stores
    self._build_store_from_config(store_name, store_config)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 4382, in _build_store_from_config
    new_store = Store.build_store_from_config(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/store/store.py", line 268, in build_store_from_config
    new_store = instantiate_class_from_config(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/util.py", line 96, in instantiate_class_from_config
    class_instance = class_(**config_with_defaults)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/store/metric_store.py", line 57, in __init__
    super().__init__(store_backend=store_backend, store_name=store_name)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/store/store.py", line 56, in __init__
    self._store_backend = instantiate_class_from_config(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/util.py", line 96, in instantiate_class_from_config
    class_instance = class_(**config_with_defaults)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/great_expectations/data_context/store/database_store_backend.py", line 97, in __init__
    table = Table(table_name, meta, autoload=True, autoload_with=self.engine)
  File "<string>", line 2, in __new__
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 774, in reflect_table
    for col_d in self.get_columns(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/snowflake/sqlalchemy/snowdialect.py", line 668, in get_columns
    schema_columns = self._get_schema_columns(connection, schema, **kw)
  File "<string>", line 2, in _get_schema_columns
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/snowflake/sqlalchemy/snowdialect.py", line 478, in _get_schema_columns
    schema_primary_keys = self._get_schema_primary_keys(
  File "<string>", line 2, in _get_schema_primary_keys
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/snowflake/sqlalchemy/snowdialect.py", line 322, in _get_schema_primary_keys
    result = connection.execute(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 777, in execute
    Error.errorhandler_wrapper(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 254, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 309, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/manuel.garrido/workspace/dataops-spike/manugarri/great_expectations/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 188, in default_errorhandler
    raise error_class(
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) SQL compilation error:
Must specify the full search path starting from database for TEMPORARY_MANUEL
[SQL: SHOW /* sqlalchemy:_get_schema_primary_keys */PRIMARY KEYS IN SCHEMA temporary_manuel]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

Checking snowflake history, i can confirm this is the query that GX executes and fails:
```
SHOW /* sqlalchemy:_get_schema_primary_keys */PRIMARY KEYS IN SCHEMA temporary_manuel
```
*(temporary_manuel is the snowflake database i am using for testing)*

**To Reproduce**
1. Setup a datacontext with a metric store as follows:

```
config_version: 3.0
anonymous_usage_statistics:
  enabled: false

datasources:
  snowflake:
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
        module_name: great_expectations.datasource.data_connector
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector
        include_schema_name: true
    class_name: Datasource
    execution_engine:
      create_temp_table: false
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
      connection_string: "snowflake://${SNOWFLAKE_USER}:${SNOWFLAKE_PASSWORD}@${SNOWFLAKE_ACCOUNT}/${SNOWFLAKE_DATABASE}?warehouse=${SNOWFLAKE_WAREHOUSE}&role=${SNOWFLAKE_ROLE}&authenticator=${SNOWFLAKE_AUTHENTICATOR}"
    module_name: great_expectations.datasource

config_variables_file_path: uncommitted/config_variables.yml

plugins_directory: plugins/

stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

  metric_store:
    class_name: MetricStore
    store_backend:
      class_name: DatabaseStoreBackend
      suppress_store_backend_id: true
      connection_string: "snowflake://${SNOWFLAKE_USER}:${SNOWFLAKE_PASSWORD}@${SNOWFLAKE_ACCOUNT}/${SNOWFLAKE_DATABASE}?warehouse=${SNOWFLAKE_WAREHOUSE}&role=${SNOWFLAKE_ROLE}&authenticator=${SNOWFLAKE_AUTHENTICATOR}"

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store
...


Seems like the function failing is sqlalchemy `_get_schema_primary_keys` which is weird because snowflake does not really have primary_keys.


As a side note, I find it a bit suspicious that the function `usage_statistics_wrapped_method` is being called when I explicitly have `anonymous_usage_statistics` set to `enabled: false`

```
2. Add an expectation and a suite. Notice that there is no need to add actions for metric store for this to fail

3.run a checkpoint `great_expectations checkpoint run checkpoint_name`

**Expected behavior**
Running a suite would store the metrics in the referenced snowflake database

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: '0.15.49'

**Additional context**

**Comment by manugarri** [comment]
**update**. 

I figured out a way to make it work, the trick was to find out the difference between defining a connection string in the datasources versus when defining the metric store.

To make a datasources snowflake work one has to do something like this:

```
datasources:
  snowflake:
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
        module_name: great_expectations.datasource.data_connector
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector
        include_schema_name: true
    class_name: Datasource
    execution_engine:
      create_temp_table: false
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
      connection_string: "snowflake://${SNOWFLAKE_USER}:${SNOWFLAKE_PASSWORD}@${SNOWFLAKE_ACCOUNT}/${SNOWFLAKE_DATABASE}?warehouse=${SNOWFLAKE_WAREHOUSE}&role=${SNOWFLAKE_ROLE}&authenticator=${SNOWFLAKE_AUTHENTICATOR}"
    module_name: great_expectations.datasource
```

However, when defining the same connection_string, **one has to add the schema the metrics table will be created on**.

```
  metric_store:
    class_name: MetricStore
    store_backend:
      class_name: DatabaseStoreBackend
      connection_string: "snowflake://${SNOWFLAKE_USER}:${SNOWFLAKE_PASSWORD}@${SNOWFLAKE_ACCOUNT}/${SNOWFLAKE_DATABASE}?warehouse=${SNOWFLAKE_WAREHOUSE}&role=${SNOWFLAKE_ROLE}&authenticator=${SNOWFLAKE_AUTHENTICATOR}&schema=great_expectations"
      table_name: ge_metrics
      key_columns: ['expectation_suite_identifier','run_name','run_time','data_asset_name', 'metric_name']

```
Running a checkpoint like this will indeed create the table. 

I will close the issue , since it seems snowflake can work as a metrics store :)
