### ISSUE TITLE
MetricResolutionError: year 0 is out of range

### ISSUE THREAD

**Issue by MMoussabbih** [great-expectations/great_expectations#7713]
### Discussed in https://github.com/great-expectations/great_expectations/discussions/7712

<div type='discussions-op-text'>

<sup>Originally posted by **MMoussabbih** April 24, 2023</sup>
Hello everyone,

I'm trying to profile a dataset using an **UserConfigurableProfiler**, but I'm getting this error : 

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/great_expectations/execution_engine/execution_engine.py", line 626, in _process_direct_and_bundled_metric_computation_configurations
    metric_fn_bundle=metric_fn_bundle_configurations
  File "/usr/local/lib/python3.7/site-packages/great_expectations/execution_engine/sparkdf_execution_engine.py", line 725, in resolve_metric_bundle
    res = df.agg(*aggregate["column_aggregates"]).collect()
  File "/mnt/yarn/usercache/hadoop/appcache/application_1682362944993_0001/container_1682362944993_0001_01_000001/pyspark.zip/pyspark/sql/dataframe.py", line 819, in collect
  File "/mnt/yarn/usercache/hadoop/appcache/application_1682362944993_0001/container_1682362944993_0001_01_000001/pyspark.zip/pyspark/serializers.py", line 151, in load_stream
  File "/mnt/yarn/usercache/hadoop/appcache/application_1682362944993_0001/container_1682362944993_0001_01_000001/pyspark.zip/pyspark/serializers.py", line 173, in _read_with_length
  File "/mnt/yarn/usercache/hadoop/appcache/application_1682362944993_0001/container_1682362944993_0001_01_000001/pyspark.zip/pyspark/serializers.py", line 452, in loads
  File "/mnt/yarn/usercache/hadoop/appcache/application_1682362944993_0001/container_1682362944993_0001_01_000001/pyspark.zip/pyspark/sql/types.py", line 1729, in <lambda>
  File "/mnt/yarn/usercache/hadoop/appcache/application_1682362944993_0001/container_1682362944993_0001_01_000001/pyspark.zip/pyspark/sql/types.py", line 823, in fromInternal
  File "/mnt/yarn/usercache/hadoop/appcache/application_1682362944993_0001/container_1682362944993_0001_01_000001/pyspark.zip/pyspark/sql/types.py", line 823, in <listcomp>
  File "/mnt/yarn/usercache/hadoop/appcache/application_1682362944993_0001/container_1682362944993_0001_01_000001/pyspark.zip/pyspark/sql/types.py", line 594, in fromInternal
  File "/mnt/yarn/usercache/hadoop/appcache/application_1682362944993_0001/container_1682362944993_0001_01_000001/pyspark.zip/pyspark/sql/types.py", line 223, in fromInternal
    def gi_yieldfrom(self):
ValueError: year 0 is out of range
`

I understood that it's related to a "weird" timestamp value in the dataset, but is there any configuration to disregard this kind of errors ?

I'm using _great_expectations==0.15.43_

Thanks in advance.</div>

**Comment by austiezr** [comment]
Hey @MMoussabbih ! Thanks for raising this. Are you able to share your environment details ( OS, datasource ), as well as an example of the data causing this error? That will help us to better investigate what may be happening / how to work around this.

**Comment by MMoussabbih** [comment]
Thanks @austiezr for your answer ! Here they are all needed information : 

- OS : LINUX (The GE Python script is inside a spark application executed in a EMR cluster)
- Datasource : A Spark Dataframe (A sample of data below)
- Schema : 
      - "**birthdate**" : _TIMESTAMP_
      - "**email_invalidation_date**" : _TIMESTAMP_
      - "**mobile_last_confirmation_date**" : _TIMESTAMP_
      - "**mobile_invalidation_date**" : _TIMESTAMP_

[Sample data.csv](https://github.com/great-expectations/great_expectations/files/11485343/Sample.data.csv)

**Comment by alexsherstinsky** [comment]
Hello, @MMoussabbih -- and thank you for reporting this issue.  The `UserConfigurableProfiler` has been discontinued in favor of a much more powerful solution: `OnboardingDataAssistant` (https://docs.greatexpectations.io/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant/).  Please try it and let us know whether or not your issue has been resolved.  Thank you for using GX!

**Comment by alexsherstinsky** [comment]
@MMoussabbih I am hoping that our suggestions helped. I am closing this issue for now. Please feel free to reopen and let us know at any time. Thank you very much for using GX!
