### ISSUE TITLE
Failed to get cardinality of column xxxx

### ISSUE THREAD

**Issue by easonktsai** [great-expectations/great_expectations#7799]
I am new for great expectations. Here is I trying to render data docs and asset profile. The following exception occured on asset profile rendering. The column Ind. Std Desc is string column and show something description. Is there any solution to fix it? Thanks!

![image](https://user-images.githubusercontent.com/127067183/235864653-400644cb-c93b-4ffa-a8f8-3dfcdb2ac0d1.png)

```
Failed to get cardinality of column Ind. Std Desc. - continuing...
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                KeyError: "'observed_value'".  Traceback: "Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 108, in render
    getattr(self, content_block_function_name)(evrs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 268, in _render_properties_table
    new_content_block = self._properties_table_renderer.render(evrs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/great_expectations/render/renderer/content_block/profiling_column_properties_table_content_block.py", line 40, in render
    new_rows = [
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/great_expectations/render/renderer/content_block/profiling_column_properties_table_content_block.py", line 41, in <listcomp>
    get_renderer_impl(expectation_type, renderer_type)[1](
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 15, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py", line 359, in _descriptive_column_properties_table_distinct_count_row_renderer
    observed_value = result.result["observed_value"]
KeyError: 'observed_value'
".
An unexpected Exception occurred during data docs rendering.  Because of this error, certain parts of data docs will not be rendered properly and/or may not appear altogether.  Please use the trace, included in this message, to diagnose and repair the underlying issue.  Detailed information follows:
                TypeError: "Object of type date is not JSON serializable".  Traceback: "Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 108, in render
    getattr(self, content_block_function_name)(evrs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 386, in _render_value_counts_bar_chart
    return get_renderer_impl(
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/great_expectations/render/renderer/renderer.py", line 15, in inner_func
    return renderer_fn(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py", line 308, in _descriptive_value_counts_bar_chart_renderer
    chart = bars.to_json()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/altair/utils/schemapi.py", line 373, in to_json
    dct = self.to_dict(validate=validate, ignore=ignore, context=context)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/altair/vegalite/v4/api.py", line 2020, in to_dict
    return super().to_dict(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/altair/vegalite/v4/api.py", line 374, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/altair/vegalite/v4/api.py", line 97, in _prepare_data
    data = _consolidate_data(data, context)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/altair/vegalite/v4/api.py", line 64, in _consolidate_data
    name = _dataset_name(values)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/altair/vegalite/v4/api.py", line 37, in _dataset_name
    values_json = json.dumps(values, sort_keys=True)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
".
```

**Comment by austiezr** [comment]
Hey @easonktsai! Thanks for raising this. Are you able to share your GX version, environment details (OS, datasource), and an example of the data in this column? That will help us to investigate what may be happening here.

**Comment by easontsai** [comment]
Hi @austiezr 

GX version: 0.16.10
databricks runtime version: 11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12)

here is code snippets 
```py
df = spark.read.format('csv') \
    .options(header='true', inferschema='true') \
    .load(f"abfss://{container_name}@{storage_account_name}.dfs.core.windows.net/{path}")

df_ge = ge.dataset.SparkDFDataset(df)

expectation_suite_on_profiling, validation_result_on_profiling = BasicDatasetProfiler.profile(df_ge)
document_model = ProfilingResultsPageRenderer().render(validation_result_on_profiling)

# render data asset profile html
displayHTML(DefaultJinjaPageView().render(document_model))

# data asset profile html
data_asset_profile = DefaultJinjaPageView().render(document_model)
print(data_asset_profile)
```

I use spark to read csv file from azure blob storage account in databricks, and use 
***df_ge = ge.dataset.SparkDFDataset(df)*** convert to sparkDFDataset for asset profile

And here is the exception column like

| column name   | value | 
| :----- | :--: |
|  Ind. Std Desc. |  3AA0xx010001  | 
|  |  3AA0aa010001  |
|  |  3AA0bb010001  |
|  |  .......  |

all of value are kind of this pattern.

As stated above, that occured asset profile throw exception. I'm trying to modify column to single word, asset profile work perfectly. well, column name contains space or dot will disrupt the GX asset profile rendering?

**Comment by alexsherstinsky** [comment]
Hello, @easonktsai -- thank you very much for providing the information about your environment.  I apologize, but we should have been more clear with the fact that the "dataset" API and the "BasicDatasetProfiler" were part of GX V2 and are no longer supported.  The recommended approach now is to use the "Fluent Datasources" API for connecting to data (`Datasource`) and to use the different available `DataAsset` methods for breaking that data up into `Batch` objects and running validations on them.  Moreover, for profiling your dataset that results in a practical `ExpectationSuite` generated automatically, the `OnboardingDataAssistant` will be of significant help.  Please see `https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview` for connecting to data as well as `https://docs.greatexpectations.io/docs/guides/expectations/data_assistants/how_to_create_an_expectation_suite_with_the_onboarding_data_assistant` for how to utilize the `OnboardingDataAssistant` for obtaining a good `ExpectationSuite` quickly.

Lastly, before you rerun your experiments using the recommended approach, please -- if possible -- start with a clean Great Expectations environment.

Please let us know how the above suggestions are working for you, and also please do not hesitate to reach out in the GX Slack Community.

Thank you very much!

**Comment by alexsherstinsky** [comment]
@easonktsai I am hoping that my suggestions helped. I am closing this issue for now. Please feel free to reopen and let us know at any time. Thank you very much for using GX!
