### ISSUE TITLE
Trino: Big numbers crash all numeric Expectations -> not an integer

### ISSUE THREAD

**Issue by JustinGuese** [great-expectations/great_expectations#7814]
**Describe the bug**

When using high enough numbers (99999999999999999999999999), trino does not recognize it as number anymore and every comparison Expectation fails.

**To Reproduce**

1. Choose whatever Expectation uses numbers ( e.g. expect_column_values_to_be_between)
2. use 99999999999999999999999999 as max_value
3. TrinoException

```
io.trino.sql.parser.ParsingException: line 1:1: Invalid numeric literal: 999999999999999999999
	at io.trino.sql.tree.LongLiteral.<init>(LongLiteral.java:45)
	at io.trino.sql.tree.LongLiteral.<init>(LongLiteral.java:34)
	at io.trino.sql.parser.AstBuilder.visitIntegerLiteral(AstBuilder.java:2666)
	at io.trino.sql.parser.AstBuilder.visitIntegerLiteral(AstBuilder.java:276)
	at io.trino.sql.parser.SqlBaseParser$IntegerLiteralContext.accept(SqlBaseParser.java:17581)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.trino.sql.parser.SqlBaseBaseVisitor.visitNumericLiteral(SqlBaseBaseVisitor.java:1147)
	at io.trino.sql.parser.SqlBaseParser$NumericLiteralContext.accept(SqlBaseParser.java:10925)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.trino.sql.parser.SqlBaseBaseVisitor.visitValueExpressionDefault(SqlBaseBaseVisitor.java:1035)
	at io.trino.sql.parser.SqlBaseParser$ValueExpressionDefaultContext.accept(SqlBaseParser.java:10389)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.trino.sql.parser.AstBuilder.visitPredicated(AstBuilder.java:1791)
	at io.trino.sql.parser.AstBuilder.visitPredicated(AstBuilder.java:276)
	at io.trino.sql.parser.SqlBaseParser$PredicatedContext.accept(SqlBaseParser.java:9586)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at io.trino.sql.parser.SqlBaseBaseVisitor.visitExpression(SqlBaseBaseVisitor.java:944)
	at io.trino.sql.parser.SqlBaseParser$ExpressionContext.accept(SqlBaseParser.java:9510)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.trino.sql.parser.AstBuilder.visit(AstBuilder.java:2998)
	at io.trino.sql.parser.AstBuilder.visitExecute(AstBuilder.java:827)
	at io.trino.sql.parser.AstBuilder.visitExecute(AstBuilder.java:276)
	at io.trino.sql.parser.SqlBaseParser$ExecuteContext.accept(SqlBaseParser.java:1361)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.trino.sql.parser.AstBuilder.visitSingleStatement(AstBuilder.java:290)
	at io.trino.sql.parser.AstBuilder.visitSingleStatement(AstBuilder.java:276)
	at io.trino.sql.parser.SqlBaseParser$SingleStatementContext.accept(SqlBaseParser.java:282)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at io.trino.sql.parser.SqlParser.invokeParser(SqlParser.java:156)
	at io.trino.sql.parser.SqlParser.createStatement(SqlParser.java:85)
	at io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:55)
	at io.trino.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:180)
	at io.trino.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:149)
	at io.trino.$gen.Trino_380_e_3____20230502_143533_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Expected behavior**

Still works

**Environment (please complete the following information):**
 - Operating System: All
 - Great Expectations Version: version 0.16.10
 - Trino version: 380-e.3

**Additional context**

Solution proposal: In the part where the Trino max is calculated, check if one number is bigger than 999999999999999999.
This is the last number that works in Trino, after that the error occurs. 
If the number is bigger, divide both numbers by e.g. 10000000000000.
The logic condition should still remain the same

**Comment by austiezr** [comment]
Hey @JustinGuese! Thanks for raising this. We've captured this for our internal backlog; if you'd like to give any further context, I'll leave this Issue open for the next week.
