### ISSUE TITLE
error 'list' object has no attribute 'format' when running expect_queried_column_list_to_be_unique

### ISSUE THREAD

**Issue by marcuselad** [great-expectations/great_expectations#7883]
**Describe the bug**
 I encountered an error while running expectation 
expect_queried_column_list_to_be_unique with metric query_templeate_values.py.
It worked fine before the addition of 'get_query' method.

**To Reproduce**
Running expectation expect_queried_column_list_to_be_unique with kwargs: column_list with list of column names separated by commas.

**Expected behavior**
Formatting the query with column_list provided

**Environment (please complete the following information):**
 - Operating System:  Windows
 - Great Expectations Version: 0.16.10
 - ExecutionEngine: SqlAlchemy
 - Driver: Vertica

**Additional context**
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\EladM\data_quality_monitoring\venv\lib\site-packages\great_expectations\execution_engine\execution_engine.py", line 543, in _process_direct_and_bundled_metric_computation_configurations
] = metric_computation_configuration.metric_fn( # type: ignore[misc] # F not callable
File "C:\Users\EladM\data_quality_monitoring\venv\lib\site-packages\great_expectations\expectations\metrics\metric_provider.py", line 50, in inner_func
return metric_fn(*args, **kwargs)
File "C:\Users\EladM\data_quality_monitoring\venv\lib\site-packages\great_expectations\expectations\metrics\query_metrics\query_template_values.py", line 71, in _sqlalchemy
query = cls.get_query(query, template_dict, f"({selectable})")
File "C:\Users\EladM\data_quality_monitoring\venv\lib\site-packages\great_expectations\expectations\metrics\query_metrics\query_template_values.py", line 30, in get_query
template_dict_reformatted = {
File "C:\Users\EladM\data_quality_monitoring\venv\lib\site-packages\great_expectations\expectations\metrics\query_metrics\query_template_values.py", line 31, in
k: v.format(active_batch=selectable) for k, v in template_dict.items()
AttributeError: 'list' object has no attribute 'format'

File "C:\Users\EladM\data_quality_monitoring\venv\lib\site-packages\great_expectations\validator\validation_graph.py", line 276, in _resolve
self._execution_engine.resolve_metrics(
File "C:\Users\EladM\data_quality_monitoring\venv\lib\site-packages\great_expectations\execution_engine\execution_engine.py", line 278, in resolve_metrics
return self._process_direct_and_bundled_metric_computation_configurations(
File "C:\Users\EladM\data_quality_monitoring\venv\lib\site-packages\great_expectations\execution_engine\execution_engine.py", line 547, in _process_direct_and_bundled_metric_computation_configurations
raise gx_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: 'list' object has no attribute 'format'

**Comment by tjholsman** [comment]
Hi @marcuselad, thanks for reaching out! Can you share the code you're using to configure the expectation? This [expectation](https://greatexpectations.io/expectations/expect_queried_column_list_to_be_unique?filterType=Backend%20support&gotoPage=1&showFilters=true&viewType=Summary) expects a `dict` called `template_dict` with a key `column_list` as its argument.

**Comment by marcuselad** [comment]
Hi, I'm just using the expectation with a dict template_dict that contains an argument column_list of type list. When column list is a list of columns. I believe get_query method assumes column_list is of type string, with columns names separated by commas.
Before adding this method I could use this expectation with list type column_list.

**Comment by tjholsman** [comment]
@marcuselad can you share code examples of what you mean?

**Comment by tyler-hoffman** [comment]
I'm closing this ticket because we haven't received a reply in two weeks. @marcuselad, please reopen if you are still running into issues and can share a code example
