### ISSUE TITLE
$PARAMETER.<parameter_in_question> key Giving Error

### ISSUE THREAD

**Issue by franciskuttivelil** [great-expectations/great_expectations#8688]
I am running the following Expectations but it is giving an error

Below are the expectation configurations. These expectation configuration were created using an Rule Based Profiler

```
[
  {
    "kwargs": {
      "min_value": 1,
      "max_value": 1,
      "mostly": 1
    },
    "meta": {
      "profiler_details": {
        "metric_configuration": {
          "metric_name": "table.row_count",
          "domain_kwargs": {},
          "metric_value_kwargs": null
        },
        "num_batches": 1
      }
    },
    "expectation_type": "expect_table_row_count_to_be_between"
  },
  {
    "kwargs": {
      "column": "spend",
      "min_value": {
        "$PARAMETER": "0.1 * mean_value",
        "$PARAMETER.mean_value": 2905
      },
      "max_value": {
        "$PARAMETER": "1.5 * mean_value",
        "$PARAMETER.mean_value": 2905
      },
      "mostly": 1
    },
    "meta": {
      "profiler_details": {
        "metric_configuration": {
          "metric_name": "column.mean",
          "domain_kwargs": {
            "column": "spend"
          },
          "metric_value_kwargs": null
        },
        "num_batches": 1
      }
    },
    "expectation_type": "expect_column_mean_to_be_between"
  },
  {
    "kwargs": {
      "column": "impressions",
      "min_value": {
        "$PARAMETER": "0.1 * mean_value",
        "$PARAMETER.mean_value": 52035
      },
      "max_value": {
        "$PARAMETER": "1.5 * mean_value",
        "$PARAMETER.mean_value": 52035
      },
      "mostly": 1
    },
    "meta": {
      "profiler_details": {
        "metric_configuration": {
          "metric_name": "column.mean",
          "domain_kwargs": {
            "column": "impressions"
          },
          "metric_value_kwargs": null
        },
        "num_batches": 1
      }
    },
    "expectation_type": "expect_column_mean_to_be_between"
  }
]
```

The code used to run the above Expectation Configuration

```
suite = context_ge.create_expectation_suite(expectation_suite_name=suite_name,overwrite_existing=True)
for expectation in expectation_configurations:
  suite.add_expectation(expectation_configuration=expectation)
  
context_ge.save_expectation_suite(suite, suite_name)

checkpoint = ge.checkpoint.SimpleCheckpoint(
    name=client_name+"_checkpoint",
    data_context=context_ge,
    validations=[{"batch_request":batch_request_yesterday, "expectation_suite_name":suite_name}],
    action_list=[{"name": "store_validation_result","action": {"class_name": "StoreValidationResultAction"}}],
)

checkpoint_result = checkpoint.run()
```

The above code gives the below error

```
Traceback (most recent call last):
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/evaluation_parameters.py", line 200, in evaluate_stack
    evaluated = int(op)
ValueError: invalid literal for int() with base 10: 'mean_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/evaluation_parameters.py", line 207, in evaluate_stack
    evaluated = float(op)
ValueError: could not convert string to float: 'mean_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/evaluation_parameters.py", line 437, in parse_evaluation_parameter
    result = EXPR.evaluate_stack(EXPR.exprStack)
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/evaluation_parameters.py", line 175, in evaluate_stack
    op2 = self.evaluate_stack(s)
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/evaluation_parameters.py", line 222, in evaluate_stack
    raise e
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/evaluation_parameters.py", line 214, in evaluate_stack
    evaluated = dateutil.parser.parse(op)
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: mean_value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/interpreter-input-5c9dc575-4984-4235-ac5e-733cc1f2c3ff.tmp", line 309, in <module>
    checkpoint_result = checkpoint.run()
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/checkpoint/checkpoint.py", line 1260, in run
    return super().run(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 260, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/checkpoint/checkpoint.py", line 304, in run
    self._run_validation(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/checkpoint/checkpoint.py", line 529, in _run_validation
    async_validation_operator_result = async_executor.submit(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/async_executor.py", line 105, in submit
    return AsyncResult(value=fn(*args, **kwargs))
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 382, in run
    async_executor.submit(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/async_executor.py", line 105, in submit
    return AsyncResult(value=fn(*args, **kwargs))
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/validator/validator.py", line 1662, in validate
    expectation.process_evaluation_parameters(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/expectation_configuration.py", line 1044, in process_evaluation_parameters
    evaluation_args, _ = build_evaluation_parameters(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/evaluation_parameters.py", line 258, in build_evaluation_parameters
    parameter_value = parse_evaluation_parameter(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/evaluation_parameters.py", line 445, in parse_evaluation_parameter
    raise EvaluationParameterError(
great_expectations.exceptions.exceptions.EvaluationParameterError: Error while evaluating evaluation parameter expression: Unknown string format: mean_value
Script failed with status: 1
```

The error is referencing the below part of the expectation configuration
```
  "min_value": {
        "$PARAMETER": "0.1 * mean_value",
        "$PARAMETER.mean_value": 52035
      },
```

I am following [this documentation](https://docs.greatexpectations.io/docs/terms/evaluation_parameter/#use-cases) to create the above code.

**Environment (please complete the following information):**
 - Operating System: Centos 7
 - Great Expectations Version: 0.17.5
 - Data Source: Redshift
 - Cloud environment: AWS

**Comment by austiezr** [comment]
Hey @franciskuttivelil ! Thanks for reaching out. We'll investigate this behavior and be in touch.

**Comment by franciskuttivelil** [comment]
@austiezr Thanks for your prompt reply! Wondering when you or your team will have a chance to look at this issue? I’m struggling to resolve it.

**Comment by HaebichanGX** [comment]
Hi @franciskuttivelil this just has to do with your formatting. For the string substitutions, you need to write it like this: 

`kwargs= {
                                          "column": "High",
                                          "min_value": {
                                            "$PARAMETER": "mean_value",
                                            "$PARAMETER.mean_value": 2905 * 0.1
                                          },
                                          "max_value": {
                                            "$PARAMETER": "mean_value",
                                            "$PARAMETER.mean_value": 2905 * 0.5
                                          },
                                          "mostly": 1
                                        }`

**Comment by franciskuttivelil** [comment]
@HaebichanGX Just adding here what we discussed on slack.

Below is a snippet of the rule based profiler i use.

```
 expectation_configuration_builders:
      - expectation_type: expect_column_mean_to_be_between
        class_name: DefaultExpectationConfigurationBuilder
        module_name: great_expectations.rule_based_profiler.expectation_configuration_builder
        column: $domain.domain_kwargs.column
        min_value:
          $PARAMETER: minvalue
          $PARAMETER.minvalue: $parameter.mean.value[0] * 10
        max_value:
          $PARAMETER: maxvalue
          $PARAMETER.maxvalue: $parameter.mean.value[0] * 20
        mostly: $variables.mostly
        meta:
          profiler_details: $parameter.mean.details 
```

When I use the the syntax you suggested above, the multiplier is completely ignored and the below expectation is generated. If the mutiplier was being used, the 2 numbers would have been different

```
"kwargs": {
        "column": "spend",
        "max_value": {
          "$PARAMETER": "maxvalue",
          "$PARAMETER.maxvalue": 5545
        },
        "min_value": {
          "$PARAMETER": "minvalue",
          "$PARAMETER.minvalue": 5545
```

Also, adding some context on why Im using a rule based profiler
1. I want to compare today's data with the mean of last 7 days data before it
2. For e.g. The mean of last 7 days spend is 100. So, today's spend should be between 50 and 150
3. So, I run the profiler on last 7 days' data to generate expectations with bespoke min and max values. Then I run these expectations on today's data

**Comment by franciskuttivelil** [comment]
@austiezr Wondering if this ticket has been assigned to anyone. Has been a long time since I raised it.

**Comment by molliemarie** [comment]
Hello @franciskuttivelil. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
