### ISSUE TITLE
Snowflake datacontext with connection parameter throws an error.

### ISSUE THREAD

**Issue by stavanmehta** [great-expectations/great_expectations#8731]
**Describe the bug**
snowflake datacontext with connection parameter has defect?
connection_string should be optional if we pass connection parameters like user, password, schema, role, db.

**To Reproduce**

1. Get the gx context
2. Add new datasource connection using context.sources.add_snowflake()
3. Instead of using connection_string, try to add connection parameters like, user, password, account, database, schema, warehouse and role

**Expected behavior**
It should add new snowflake datasource

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: great_expectations==0.17.16
 - Data Source: Snowflake
 - Cloud environment: AWS

**Additional context**
Error message
```
Traceback (most recent call last):
  File "/Users/stavan.mehta/projects/spaceship/spaceship/lib/python3.11/site-packages/great_expectations/datasource/fluent/snowflake_datasource.py", line 133, in get_engine
    connection_string = model_dict.pop("connection_string")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'connection_string'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stavan.mehta/projects/spaceship/spaceship/lib/python3.11/site-packages/great_expectations/datasource/fluent/sql_datasource.py", line 1069, in test_connection
    engine: sqlalchemy.Engine = self.get_engine()
                                ^^^^^^^^^^^^^^^^^
  File "/Users/stavan.mehta/projects/spaceship/spaceship/lib/python3.11/site-packages/great_expectations/datasource/fluent/snowflake_datasource.py", line 143, in get_engine
    raise SQLDatasourceError(
great_expectations.datasource.fluent.sql_datasource.SQLDatasourceError: Unable to create a SQLAlchemy engine from connection_string: None due to the following exception: 'connection_string'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stavan.mehta/projects/spaceship/gx_cloud_setup.py", line 24, in <module>
    datasource = context.sources.add_snowflake(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stavan.mehta/projects/spaceship/spaceship/lib/python3.11/site-packages/great_expectations/datasource/fluent/sources.py", line 472, in add_datasource
    datasource.test_connection()
  File "/Users/stavan.mehta/projects/spaceship/spaceship/lib/python3.11/site-packages/great_expectations/datasource/fluent/sql_datasource.py", line 1072, in test_connection
    raise TestConnectionError(
great_expectations.datasource.fluent.interfaces.TestConnectionError: Attempt to connect to datasource failed with the following error message: Unable to create a SQLAlchemy engine from connection_string: None due to the following exception: 'connection_string'
```

**Comment by rachhouse** [comment]
Hey @stavanmehta! Thanks again for raising this bug, we've captured it for review. 🚀

**Comment by Kilo59** [comment]
Sorry for the delay @stavanmehta 

The [fix has been implemented](https://github.com/great-expectations/great_expectations/pull/8816), and it should be part of our next release on Thursday.
