### ISSUE TITLE
Rule Based Profiler Not working when DX Cloud enabled

### ISSUE THREAD

**Issue by franciskuttivelil** [great-expectations/great_expectations#8789]
**Describe the bug**
I have created a rule based profiler that works using with ephermal data context. But when i use the same profiler with ge.get_context(), it doesn't work

**To Reproduce**
When I use the below data context, the rule based profiler works
```
project_config = DataContextConfig(store_backend_defaults=S3StoreBackendDefaults(default_bucket_name=s3_bucket))
context_ge = EphemeralDataContext(project_config=project_config)
```

When I use the below data context, the rule based profiler doesn't work
`context_ge = ge.get_context(cloud_mode=True)`

Below is the rule based profiler
```
name: My Profiler
config_version: 1.0
# </snippet>

# <snippet name="tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py variables and rule name">
variables:
  false_positive_rate: 0.01
  mostly: 1.0
  min_multiplier: 0.1
  max_multiplier: 1.5
  parameter_text: $PARAMETER

rules:
  row_count_rule:
# </snippet>
# <snippet name="tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py row_count_rule domain_builder">
    domain_builder:
        class_name: TableDomainBuilder
# </snippet>
# <snippet name="tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py row_count_rule parameter_builders">
    parameter_builders:
      - name: row_count_range
        class_name: NumericMetricRangeMultiBatchParameterBuilder
        metric_name: table.row_count
        metric_domain_kwargs: $domain.domain_kwargs
        false_positive_rate: $variables.false_positive_rate
        truncate_values:
          lower_bound: 0
        round_decimals: 0
# </snippet>
# <snippet name="tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py row_count_rule expectation_configuration_builders">
    expectation_configuration_builders:
      - expectation_type: expect_table_row_count_to_be_between
        class_name: DefaultExpectationConfigurationBuilder
        module_name: great_expectations.rule_based_profiler.expectation_configuration_builder
        min_value: $parameter.row_count_range.value[0]
        max_value: $parameter.row_count_range.value[1]
        mostly: $variables.mostly
        meta:
          profiler_details: $parameter.row_count_range.details
# </snippet>
# </snippet>
# <snippet name="tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py column_ranges_rule domain_builder">
  column_ranges_rule:
    domain_builder:
      class_name: ColumnDomainBuilder
      include_semantic_types:
        - numeric
# </snippet>
# <snippet name="tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py column_ranges_rule parameter_builders">
    parameter_builders:
      - name: mean
        class_name: NumericMetricRangeMultiBatchParameterBuilder
        metric_name: column.mean
        metric_domain_kwargs: $domain.domain_kwargs
        false_positive_rate: $variables.false_positive_rate
        truncate_values:
          lower_bound: 0
        round_decimals: 0
# </snippet>
# <snippet name="tests/integration/docusaurus/expectations/advanced/multi_batch_rule_based_profiler_example.py column_ranges_rule expectation_configuration_builders">
    expectation_configuration_builders:
      - expectation_type: expect_column_mean_to_be_between
        class_name: DefaultExpectationConfigurationBuilder
        module_name: great_expectations.rule_based_profiler.expectation_configuration_builder
        column: $domain.domain_kwargs.column
        min_value:
          $PARAMETER: minvalue
          $PARAMETER.minvalue: $parameter.mean.value[0]
        max_value:
          $PARAMETER: maxvalue
          $PARAMETER.maxvalue: $parameter.mean.value[0]
        mostly: $variables.mostly
        meta:
          profiler_details: $parameter.mean.details
# </snippet>
# </snippet>
```

Below is the error generated

```
Calculating Metrics:  50%|█████     | 1/2 [00:00<00:00, 39.40it/s][A[A
Calculating Metrics:  50%|█████     | 1/2 [00:00<00:00, 39.24it/s]
Exceptions
{('table.row_count', 'batch_id=1beacf14f974ce11091024ae519b0824', ()): {'metric_configuration': {
  "metric_name": "table.row_count",
  "metric_domain_kwargs": {
    "batch_id": "1beacf14f974ce11091024ae519b0824"
  },
  "metric_domain_kwargs_id": "batch_id=1beacf14f974ce11091024ae519b0824",
  "metric_value_kwargs": {},
  "metric_value_kwargs_id": [],
  "id": [
    "table.row_count",
    "batch_id=1beacf14f974ce11091024ae519b0824",
    []
  ]
}, 'num_failures': 3, 'exception_info': {{'exception_traceback': 'Traceback (most recent call last):\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context\n    self.dialect.do_execute(\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute\n    cursor.execute(statement, parameters)\npsycopg2.errors.UndefinedTable: relation "gx_temp_3048f0d9" does not exist\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 563, in _process_direct_and_bundled_metric_computation_configurations\n    ] = self.resolve_metric_bundle(\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 1134, in resolve_metric_bundle\n    res = self.execute_query(sa_query_object).fetchall()\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 1450, in execute_query\n    result = connection.execute(query)\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1380, in execute\n    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection\n    return connection._execute_clauseelement(\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement\n    ret = self._execute_context(\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context\n    self._handle_dbapi_exception(\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception\n    util.raise_(\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_\n    raise exception\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context\n    self.dialect.do_execute(\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "gx_temp_3048f0d9" does not exist\n\n[SQL: SELECT count(*) AS "table.row_count" \nFROM gx_temp_3048f0d9]\n(Background on this error at: https://sqlalche.me/e/14/f405)\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/validator/validation_graph.py", line 285, in _resolve\n    self._execution_engine.resolve_metrics(\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 283, in resolve_metrics\n    return self._process_direct_and_bundled_metric_computation_configurations(\n  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 568, in _process_direct_and_bundled_metric_computation_configurations\n    raise gx_exceptions.MetricResolutionError(\ngreat_expectations.exceptions.exceptions.MetricResolutionError: (psycopg2.errors.UndefinedTable) relation "gx_temp_3048f0d9" does not exist\n\n[SQL: SELECT count(*) AS "table.row_count" \nFROM gx_temp_3048f0d9]\n(Background on this error at: https://sqlalche.me/e/14/f405)\n', 'exception_message': '(psycopg2.errors.UndefinedTable) relation "gx_temp_3048f0d9" does not exist\n\n[SQL: SELECT count(*) AS "table.row_count" \nFROM gx_temp_3048f0d9]\n(Background on this error at: https://sqlalche.me/e/14/f405)', 'raised_exception': True}}}}
occurred while resolving metrics.
table.row_count was not found in the resolved Metrics for ParameterBuilder.


                                                              [A
Generating Expectations:   0%|          | 0/2 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/tmp/interpreter-input-2fc7b1a4-8a3c-4a1c-b578-a33415d36e9e.tmp", line 170, in <module>
    result = rule_based_profiler.run(batch_request=batch_request_last7days)
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 260, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/rule_based_profiler/rule_based_profiler.py", line 357, in run
    raise err
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/rule_based_profiler/rule_based_profiler.py", line 336, in run
    rule_state = rule.run(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/util.py", line 219, in compute_delta_t
    return func(*args, **kwargs)
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/rule_based_profiler/rule/rule.py", line 159, in run
    parameter_builder.build_parameters(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py", line 191, in build_parameters
    parameter_computation_result: Attributes = parameter_computation_impl(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py", line 402, in _build_parameters
    self._estimate_metric_value_range(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py", line 634, in _estimate_metric_value_range
    numeric_range_estimator.get_numeric_range_estimate(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/rule_based_profiler/estimators/numeric_range_estimator.py", line 74, in get_numeric_range_estimate
    return self._get_numeric_range_estimate(
  File "/usr/share/tomcat8/.local/lib/python3.8/site-packages/great_expectations/rule_based_profiler/estimators/bootstrap_numeric_range_estimator.py", line 63, in _get_numeric_range_estimate
    raise gx_exceptions.ProfilerExecutionError(
great_expectations.exceptions.exceptions.ProfilerExecutionError: Estimator "BootstrapNumericRangeEstimator" does not support DateTime/TimeStamp data types.
Script failed with status: 1
```

**Expected behavior**
Below is the expectation configuration generated when the rule based profiler works with Ephermal data context

```
{
  "expectation_suite_name": "default_suite_name",
  "expectations": [
    {
      "kwargs": {
        "max_value": 1,
        "min_value": 1,
        "mostly": 1.0
      },
      "expectation_type": "expect_table_row_count_to_be_between",
      "meta": {
        "profiler_details": {
          "metric_configuration": {
            "domain_kwargs": {},
            "metric_name": "table.row_count",
            "metric_value_kwargs": null
          },
          "num_batches": 1
        }
      }
    },
    {
      "kwargs": {
        "column": "kpi1",
        "max_value": {
          "$PARAMETER": "maxvalue",
          "$PARAMETER.maxvalue": 5100
        },
        "min_value": {
          "$PARAMETER": "minvalue",
          "$PARAMETER.minvalue": 5100
        },
        "mostly": 1.0
      },
      "expectation_type": "expect_column_mean_to_be_between",
      "meta": {
        "profiler_details": {
          "metric_configuration": {
            "domain_kwargs": {
              "column": "kpi1"
            },
            "metric_name": "column.mean",
            "metric_value_kwargs": null
          },
          "num_batches": 1
        }
      }
    },
    {
      "kwargs": {
        "column": "kpi2",
        "max_value": {
          "$PARAMETER": "maxvalue",
          "$PARAMETER.maxvalue": 83293
        },
        "min_value": {
          "$PARAMETER": "minvalue",
          "$PARAMETER.minvalue": 83293
        },
        "mostly": 1.0
      },
      "expectation_type": "expect_column_mean_to_be_between",
      "meta": {
        "profiler_details": {
          "metric_configuration": {
            "domain_kwargs": {
              "column": "kpi2"
            },
            "metric_name": "column.mean",
            "metric_value_kwargs": null
          },
          "num_batches": 1
        }
      }
    }
  ],
  "data_asset_type": null,
  "ge_cloud_id": null,
  "meta": {
    "great_expectations_version": "0.17.19"
  }
}
```

**Environment (please complete the following information):**
 - Operating System: Cenos OS 7
 - Great Expectations Version: 0.17.19
 - Data Source: Redhsift
 - Cloud environment: AWS

**Comment by r34ctor** [comment]
Hi @franciskuttivelil, thanks for raising this! We've captured this for review.

**Comment by molliemarie** [comment]
Hello @franciskuttivelil. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
