### ISSUE TITLE
expect_column_values_to_be_in_set running against snowflake throwing (builtins.NotImplementedError) 'post-compile' bind parameters are not supported with the 'numeric' paramstyle at this time.

### ISSUE THREAD

**Issue by evie-vacasa** [great-expectations/great_expectations#8795]
**Describe the bug**
I have a state column with US state abbreviations and running gx expectation 'expect_column_values_to_be_in_set' with value_set containing list of two character strings for state abbrev.

The sql being generated by great expectations is failing with a 'not implemented' error. I've used this expectation elsewhere without issue and when I remove this expectation all the other expectations pass without issue.

**To Reproduce**
1. Execute an expect_column_values_to_be_in_set expectation against a snowflake db.
2. [great_expectations_config.pdf](https://github.com/great-expectations/great_expectations/files/12809047/great_expectations_config.pdf)

**Expected behavior**
1. query can execute without error.
I expect to run the great_expectation checkpoint and have the datadoc contain results, instead it has a long sql error for several of the results

**Environment (please complete the following information):**
 - Operating System:MacOs
 - Great Expectations Version: 0.17.20
 - Data Source: Snowflake
 - Cloud environment:n/a

**Additional context**
(builtins.NotImplementedError) 'post-compile' bind parameters are not supported with the 'numeric' paramstyle at this time. [SQL: SELECT sum(CASE WHEN ("STATE" IS NULL) THEN :1 ELSE :2 END) AS "column_values.nonnull.unexpected_count", sum(CASE WHEN ("STATE" IS NOT NULL AND ("STATE" NOT IN (__[POSTCOMPILE_STATE_1]))) THEN :3 ELSE :4 END) AS "column_values.in_set.unexpected_count", sum(CASE WHEN ("STRATEGIC_COHORT" IS NULL) THEN :5 ELSE :6 END) AS "column_values.nonnull.unexpected_count", sum(CASE WHEN ("SIZE_DETAILS" IS NULL) THEN :7 ELSE :8 END) AS "column_values.nonnull.unexpected_count", sum(CASE WHEN ("SPECIFIC_LOCATION" IS NULL) THEN :9 ELSE :10 END) AS "column_values.nonnull.unexpected_count", sum(CASE WHEN ("ID" IS NULL) THEN :11 ELSE :12 END) AS "column_values.nonnull.unexpected_count", sum(CASE WHEN ("ID" IS NOT NULL AND NOT ("ID" >= :13 AND "ID" <= :14)) THEN :15 ELSE :16 END) AS "column_values.between.unexpected_count" FROM gx_temp_87467e03]
[Show exception traceback...](https://github.com/great-expectations/great_expectations/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=#section-4-content-block-2-cell-1-2-content-2-collapse-body-a55de10e-2226-4b87-a09d-406ef2a41ef2)

Traceback (most recent call last):
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
context = constructor(
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1037, in _init_compiled
expanded_state = compiled._process_parameters_for_postcompile(
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1194, in _process_parameters_for_postcompile
raise NotImplementedError(
NotImplementedError: 'post-compile' bind parameters are not supported with the 'numeric' paramstyle at this time.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 563, in _process_direct_and_bundled_metric_computation_configurations
] = self.resolve_metric_bundle(
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 1134, in resolve_metric_bundle
res = self.execute_query(sa_query_object).fetchall()
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 1450, in execute_query
result = connection.execute(query)
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
return connection._execute_clauseelement(
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
ret = self._execute_context(
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1816, in _execute_context
self._handle_dbapi_exception(
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
util.raise_(
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
raise exception
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
context = constructor(
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1037, in _init_compiled
expanded_state = compiled._process_parameters_for_postcompile(
File "/Users/EvieCameron/Library/Caches/pypoetry/virtualenvs/data-science-quality-framework-yyCk3iqc-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1194, in _process_parameters_for_postcompile
raise NotImplementedError(
sqlalchemy.exc.StatementError: (builtins.NotImplementedError) 'post-compile' bind parameters are not supported with the 'numeric' paramstyle at this time.

**Comment by r34ctor** [comment]
Hi @evie-vacasa, thanks for raising this. We've captured this for review internally.

**Comment by HaebichanGX** [comment]
Hi @evie-vacasa I can't seem to reproduce this error (mine is running fine). Firstly, you are referencing the `great_expectations_config.pdf` which is an old, deprecated version of GX, while you are on the latest version on V17. Can you please use the latest GX version using Fluent Data Sources (FDS), and see if that fixes the issue? Here's my FDS implementation code below, which mimics your use case on Snowflake. 

```import great_expectations as gx
from great_expectations.data_context import FileDataContext
import os
base = os.getcwd()

path_to_empty_folder = base + "/my_gx_project/"

context = FileDataContext.create(project_root_dir=path_to_empty_folder)

snowflake_connection_str = (
    f"snowflake://{USER_NAME}:{PASSWORD}@{ACCOUNT_NAME}/{DATABASE_NAME}/{SCHEMA_NAME}?"
    f"warehouse={WAREHOUSE_NAME}&role={ROLE_NAME}"
)

datasource = context.sources.add_sql(name = 'snowflake_ds', connection_string = snowflake_connection_str)

asset = datasource.add_table_asset(name = 'SQL asset', table_name = 'TAXI_DATA')

batch_request = asset.build_batch_request()

validator = context.get_validator(batch_request=batch_request )

validator.expect_column_values_to_be_in_set("store_and_fwd_flag", ['Y','N'])

validator.save_expectation_suite()

checkpoint = context.add_checkpoint(name = 'sample_checkpoint', validator = validator)
checkpoint.run()

 ```

![Screenshot 2023-10-26 at 1 27 16 PM](https://github.com/great-expectations/great_expectations/assets/133805639/72a876e5-0f81-4b69-b583-4f863042c238)

**Comment by HaebichanGX** [comment]
closing this issue as no response for a week
