### ISSUE TITLE
checkpoint.run() is unable to parse a GCS path with a period in it

### ISSUE THREAD

**Issue by nirajdewani** [great-expectations/great_expectations#8963]
**Describe the bug**
`checkpoint.run()` is unable to parse a GCS path with a period in it.

**To Reproduce**
Upon following this [doc](https://github.com/great-expectations/great_expectations/blob/develop/docs/docusaurus/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md#5-build-and-run-a-checkpoint), I get a 
```
  >>> checkpoint_result = checkpoint.run()
Calculating Metrics: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.41it/s]
Error running action with name store_evaluation_params
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/great_expectations/validation_operators/validation_operators.py", line 478, in _run_actions
    action_result = self.actions[name].run(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/checkpoint/actions.py", line 100, in run
    return self._run(
           ^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/checkpoint/actions.py", line 1015, in _run
    self.data_context.store_evaluation_parameters(validation_result_suite)
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2167, in store_evaluation_parameters
    self._compile_evaluation_parameter_dependencies()
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 4740, in _compile_evaluation_parameter_dependencies
    expectation_suite_dict: dict = cast(dict, self.expectations_store.get(key))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/store/expectations_store.py", line 210, in get
    return super().get(key)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/store/store.py", line 207, in get
    value = self._store_backend.get(self.key_to_tuple(key))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/store/_store_backend.py", line 123, in get
    value = self._get(key, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 863, in _get
    raise InvalidKeyError(
great_expectations.exceptions.exceptions.InvalidKeyError: Unable to retrieve object from TupleGCSStoreBackend with the following Key: ('test_bigquery_suite', '__none__', '20231114T223144', '500796Z', 'my_bigquery_datasource-my_table_asset')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.11/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 260, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/checkpoint/checkpoint.py", line 305, in run
    self._run_validation(
  File "/venv/lib/python3.11/site-packages/great_expectations/checkpoint/checkpoint.py", line 530, in _run_validation
    async_validation_operator_result = async_executor.submit(
                                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/core/async_executor.py", line 106, in submit
    return AsyncResult(value=fn(*args, **kwargs))
                             ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/validation_operators/validation_operators.py", line 415, in run
    batch_actions_results = self._run_actions(
                            ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/validation_operators/validation_operators.py", line 508, in _run_actions
    raise e
  File "/venv/lib/python3.11/site-packages/great_expectations/validation_operators/validation_operators.py", line 478, in _run_actions
    action_result = self.actions[name].run(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/checkpoint/actions.py", line 100, in run
    return self._run(
           ^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/checkpoint/actions.py", line 1015, in _run
    self.data_context.store_evaluation_parameters(validation_result_suite)
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2167, in store_evaluation_parameters
    self._compile_evaluation_parameter_dependencies()
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 4740, in _compile_evaluation_parameter_dependencies
    expectation_suite_dict: dict = cast(dict, self.expectations_store.get(key))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/store/expectations_store.py", line 210, in get
    return super().get(key)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/store/store.py", line 207, in get
    value = self._store_backend.get(self.key_to_tuple(key))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/store/_store_backend.py", line 123, in get
    value = self._get(key, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/great_expectations/data_context/store/tuple_store_backend.py", line 863, in _get
    raise InvalidKeyError(
great_expectations.exceptions.exceptions.InvalidKeyError: Unable to retrieve object from TupleGCSStoreBackend with the following Key: ('test_bigquery_suite', '__none__', '20231114T223144', '500796Z', 'my_bigquery_datasource-my_table_asset')
```
 when the JSON file exists in GCS at 
`gs://blah/great_expectations/test_bigquery_suite/__none__/20231114T223144.500796Z/my_bigquery_datasource-my_table_asset.json`

**Expected behavior**
I expect `checkpoint.run()` to run without any errors.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.18.2
 - Data Source: BigQuery
 - Cloud environment: GCP

**Additional context**

**Comment by jhendricks-elevate** [comment]
I have a similar issue with GCS. I followed the instructions here: https://docs.greatexpectations.io/docs/oss/guides/connecting_to_your_data/fluent/database/connect_sql_source_data/?sql-database-type=bigquery 

gx has no problem putting a file here: gs://waaaah/test_bigquery_suite/__none__/20240410T160452.569315Z/file.json 

During the store_evaluation_params action i get this error:
Unable to retrieve object from TupleGCSStoreBackend with the following Key: ('test_bigquery_suite', '__none__', '20240410T160452', '569315Z', 'file') gx is publishing with a "." but then incorrectly creating the object path when trying to retrieve it

**Comment by molliemarie** [comment]
Hello @nirajdewani. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
