### ISSUE TITLE
SNSNotificationAction class has a bug, run returns str instead of Dict

### ISSUE THREAD

**Issue by ejstembler** [great-expectations/great_expectations#9269]
The [SNSNotificationAction](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/checkpoint/actions.py) class has a bug.  The `run` function ultimately returns a `str` from [util/send_sns_notification](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/checkpoint/util.py#L516-L552) instead of an expected `Dict`.

This results in a error:

```console
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/great_expectations/validation_operators/validation_operators.py", line 502, in _run_actions
    batch_actions_results[action["name"]]["class"] = action["action"][
TypeError: 'str' object does not support item assignment
[2024-01-02, 21:53:46 UTC] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/great_expectations_provider/operators/great_expectations.py", line 592, in execute
    result = self.checkpoint.run()
  File "/usr/local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 1263, in run
    return super().run(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 260, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 305, in run
    self._run_validation(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 530, in _run_validation
    async_validation_operator_result = async_executor.submit(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/core/async_executor.py", line 106, in submit
    return AsyncResult(value=fn(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/great_expectations/validation_operators/validation_operators.py", line 415, in run
    batch_actions_results = self._run_actions(
  File "/usr/local/lib/python3.9/site-packages/great_expectations/validation_operators/validation_operators.py", line 508, in _run_actions
    raise e
  File "/usr/local/lib/python3.9/site-packages/great_expectations/validation_operators/validation_operators.py", line 502, in _run_actions
    batch_actions_results[action["name"]]["class"] = action["action"][
TypeError: 'str' object does not support item assignment
```

**Comment by molliemarie** [comment]
Hello @ejstembler. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
